### PR TITLE
22-Shell-unit-test-for-kill-all-processes-failed

### LINKED ISSUE #22: Shell unit test for kill all processes failed
**Describe the bug**
Shell unit test with running `image kill -all` command failed.

**To Reproduce**
1. Go to `test` directory
2. run `testImageCommands.sh`
3.  See error:
```
ASSERT:
shunit2:ERROR testLauncherKillAllCommandWithOneImageLaunchedShouldKillAll() returned non-zero return code.
testLauncherKillCommandWithOneImageLaunchedShouldKillIt
pthread_setschedparam failed: Operation not permitted
This VM uses a separate heartbeat thread to update its internal clock
and handle events.  For best operation, this thread should run at a
higher priority, however the VM was unable to change the priority.  The
effect is that heavily loaded systems may experience some latency
issues.  If this occurs, please create the appropriate configuration
file in /etc/security/limits.d/ as shown below:

cat <<END | sudo tee /etc/security/limits.d/pharo.conf
*      hard    rtprio  2
*      soft    rtprio  2
END

and report to the pharo mailing list whether this improves behaviour.
```

**Expected behavior**
Kill command succeeds.

**Screenshots**

**Version information:**
 - OS: x86_64 GNU/Linux
 - Version: #42~20.04.1-Ubuntu

**Expected development cost**
Find a root cause of pthead_setschedparam() failure...

### PR DESCRIPTION
**Pull request by Bajger**
replaced ps command with pgrep that works more reliably

### CODE REVIEW

**Comment by Bajger** [comment]
@demarey : All sh unit tests green. Please take a look. I did simplification and put refactored functions to common sh file.

File: test/testImageCommands.sh [hunk 1]
```diff
@@ -1,82 +1,89 @@
...
+#ensure that Shell unit test library is installed
+ensureShunitIsPresent
 
-# setup commands for image manipulation
-processListCommand="runLauncherScript image processList"
-launchCommand="runLauncherScript image launch PhLTestImage"
-killAllCommand="runLauncherScript image kill --all"
-killCommand="runLauncherScript image kill PhLTestImage"
+#setup sample image name and template name
+SAMPLEIMAGE="PhLTestImage"
```
Comment (demarey) [inline test/testImageCommands.sh]: I would use SAMPLE_IMAGE to improve readability

File: test/testImageCommands.sh [hunk 2]
```diff
@@ -1,82 +1,89 @@
...
+SAMPLETEMPLATE="Pharo 8.0 - 64bit (old stable)"
```
Comment (demarey) [inline test/testImageCommands.sh]: I would use SAMPLE_TEMPLATE to improve readability

File: test/testImageCommands.sh [hunk 3]
```diff
@@ -1,82 +1,89 @@
...
+	result=$(processListCommand)
+	echo "actual: $result"
+    echo "expected (should contain): $SAMPLEIMAGE"
+	assertContains "$result" "$SAMPLEIMAGE"
+	killAllCommand
+	result=$(processListCommand)
+	assertNotContains "$result" "$SAMPLEIMAGE"
+	echo "Actual: $result"
+    echo "Not expected (should not contain): $SAMPLEIMAGE"
+	assertNotContains "$result" "$SAMPLEIMAGE"
```
Comment (demarey) [inline test/testImageCommands.sh]: duplicated assertion

File: test/testImageCommands.sh [hunk 4]
```diff
@@ -1,82 +1,89 @@
...
-	$launchCommand >/dev/null
-	result=$($processListCommand)
-	assertNotNull "$result"
-	$killAllCommand
-	result=$($processListCommand)
-	assertNull "$result"
+	launchSampleImageCommand> /dev/null
+	result=$(processListCommand)
+	echo "actual: $result"
+    echo "expected (should contain): $SAMPLEIMAGE"
```
Comment (demarey) [inline test/testImageCommands.sh]: Are the echos needed? I guess it is for debugging purposes when the assertion fails.
Does'nt the assertion provide the same kind of output? If not, it's too bad. If yes, probably echos could be removed.

**Comment by demarey** [comment]
> @demarey : All sh unit tests green. Please take a look. I did simplification and put refactored functions to common sh file.

Nice job! Thanks David.

File: test/testImageCommands.sh (hunk 1 above)
Comment (Bajger) [reply test/testImageCommands.sh]: Ok, will be renamed.

File: test/testImageCommands.sh (hunk 2 above)
Comment (Bajger) [reply test/testImageCommands.sh]: Ok, will be renamed.

File: test/testImageCommands.sh (hunk 3 above)
Comment (Bajger) [reply test/testImageCommands.sh]: Will fix!

File: test/testImageCommands.sh (hunk 4 above)
Comment (Bajger) [reply test/testImageCommands.sh]: Well, when I tested, it shown only the expected value, but not actual. I can remove for now (since I used for debugging). Maybe to consider more verbose output. I didn't find in shunit library, if there are options to show actual.

Comment (demarey) [reply test/testImageCommands.sh]: yes, it is std behaviour to ouput both expected and actual output when an assert fails. Maybe you can wrap the assert in a function to add missing echo, and reuse this function for asserting (less duplication)

Comment (Bajger) [reply test/testImageCommands.sh]: Maybe it was because the actual was empty and was shown on one line... I will try and if really missing, I can add wrapper function to show actual.

**Comment by Bajger** [comment]
@demarey Replaced assertContains, assertNotContains with printed version (will print only when assertion fails).

File: test/PharoLauncherCommonFunctions.sh [hunk 5]
```diff
@@ -44,4 +44,12 @@ runLauncherScript() {
 	pushd ..> /dev/null
 	$PHLSCRIPT $@
 	popd> /dev/null
-}
\ No newline at end of file
+}
+
+assertContainsPrinted() {
+    assertContains "Actual: \"$1\", expected: \"$2\". " "$1" "$2"
```
Comment (demarey) [inline test/PharoLauncherCommonFunctions.sh:50]: shouldn't this be as below to only print current values if assertion fails?
```bash
assertContains "$1" "$2" || echo "Actual: \"$1\", expected: \"$2\". " "$1" "$2"
```

Comment (Bajger) [reply test/PharoLauncherCommonFunctions.sh:50]: The first parameter of `assertContains` (or `assertNotContains`) is optional message, that is printed only in case, if assertion fails (documentation lacks however description of "message" behavior). Handling you're describe is already there. (I've tested with successful assertion and false assertion).

Comment (Bajger) [reply test/PharoLauncherCommonFunctions.sh:50]: When assertion fails output looks like this: 
`ASSERT:Actual: "blabla", expected: "PhLTestImage". Not found:<PhLTestImage>`
When assert is true, it doesn't print anything.

Comment (demarey) [reply test/PharoLauncherCommonFunctions.sh:50]: perfect! :)

**Comment by Bajger** [comment]
Christophe, if there isn't anything else, please approve :) So it can be merged and I'll remove feature branch then. Thanks a lot!

**Review by demarey — APPROVED** [review]
